-- Initial schema for wpm_pacer: stores saved reading passages.
CREATE TABLE passages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(120),
    content     TEXT           NOT NULL,
    wpm         INTEGER        NOT NULL,
    source_type VARCHAR(16)    NOT NULL,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT pk_passages PRIMARY KEY (id),
    CONSTRAINT ck_passages_wpm CHECK (wpm BETWEEN 60 AND 1500),
    CONSTRAINT ck_passages_source_type CHECK (source_type IN ('MANUAL', 'PASTE', 'FILE', 'OCR'))
);

-- History list is always ordered by recency; index supports it.
CREATE INDEX idx_passages_created_at ON passages (created_at DESC);
